/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#005321",
        "secondary-fixed-dim": "#4ae176",
        "tertiary": "#3130c0",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "surface": "#f9f9ff",
        "background": "#f9f9ff",
        "inverse-primary": "#c3c0ff",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#edf0ff",
        "surface-container": "#e9edff",
        "surface-bright": "#f9f9ff",
        "tertiary-container": "#4b4dd8",
        "on-surface": "#141b2b",
        "surface-container-high": "#e1e8fd",
        "primary-fixed": "#e2dfff",
        "on-tertiary": "#ffffff",
        "on-background": "#141b2b",
        "surface-container-highest": "#dce2f7",
        "on-tertiary-fixed": "#07006c",
        "tertiary-fixed": "#e1e0ff",
        "secondary-fixed": "#6bff8f",
        "outline": "#777587",
        "primary-container": "#4f46e5",
        "surface-container-low": "#f1f3ff",
        "secondary": "#006e2f",
        "on-secondary": "#ffffff",
        "surface-dim": "#d3daef",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#c0c1ff",
        "primary": "#3525cd",
        "on-surface-variant": "#464555",
        "outline-variant": "#c7c4d8",
        "on-secondary-fixed": "#002109",
        "on-primary-fixed-variant": "#3323cc",
        "primary-fixed-dim": "#c3c0ff",
        "secondary-container": "#6bff8f",
        "error-container": "#ffdad6",
        "on-primary-container": "#dad7ff",
        "surface-variant": "#dce2f7",
        "on-secondary-container": "#007432",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#0f0069",
        "surface-tint": "#4d44e3",
        "on-tertiary-container": "#d9d8ff",
        "inverse-surface": "#293040",
        brand: {
          50: '#f0f7ff',
          100: '#e0effe',
          200: '#bae0fd',
          300: '#7cc8fc',
          400: '#36adf8',
          500: '#0c93e9',
          600: '#0074c7',
          700: '#015da1',
          800: '#064f85',
          900: '#0b426e',
          950: '#072a49',
        },
      },
      fontFamily: {
        headline: ['var(--font-manrope)', 'sans-serif'],
        body: ['var(--font-inter)', 'sans-serif'],
        label: ['var(--font-inter)', 'sans-serif'],
        sans: ['var(--font-inter)', 'system-ui', 'sans-serif'],
      },
      borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
  ],
};
